### ISSUE TITLE
Test net

### ISSUE THREAD

**Issue by Alek-dr** [preethamsp/tutorial.gtsrb.torch.old#1]
Help please
I can train NN and save
then i load and try to test, but that's the way to test net on ONE picture?

**Comment by preethamsp** [comment]
yes. You'd need to load your model to test even on a single picture
```
m = torch.load('saved/mode/path')
im = image.load('/path/to/image')
p = m:forward(im)
```

**Comment by Alek-dr** [comment]
this is obvious, but it does not work :(

**Comment by preethamsp** [comment]
can you post a snippet and the error log from the console?

**Comment by Alek-dr** [comment]
This works:

local im = image.load(".../22/00754.ppm")

local t = require 'transforms'
model:remove(28)

local valPreprocess = t.Compose{
    t.Scale(48),
    t.ColorNormalize(t.meanstd),
    t.CenterCrop(48) }

im = valPreprocess(im)
local IMAGE = torch.Tensor(1, 3, 48, 48)
IMAGE[1] = im
IMAGE = IMAGE:cuda()
print(model:forward(IMAGE))
